In [4]:
import numpy as np

In [11]:
tb = np.zeros((50,50))

In [12]:
tw = np.ones((50,50))

In [23]:
np.concatenate((np.concatenate((tb, tw), axis=1), np.concatenate((tw, tb), axis=1)) ,axis=0)

array([[0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.]])

In [20]:
 chess= np.tile(np.concatenate((np.concatenate((tb, tw), axis=1), np.concatenate((tw, tb), axis=1)) ,axis=0),(50,50))  

In [22]:
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np

plt.imsave('filename.png', np.array(chess).reshape(5000,5000), cmap=cm.gray)

In [25]:
np.concatenate((np.concatenate((tb, tw), axis=1), np.concatenate((tb, tw), axis=1)) ,axis=0).shape

(100, 100)

In [26]:
tb = np.zeros((50,50))
tw = np.ones((50,50))
strips= np.tile(np.concatenate((np.concatenate((tb, tw), axis=1), np.concatenate((tb, tw), axis=1)) ,axis=0),(50,50))  

In [29]:
plt.imsave('strips.png', np.array(strips).reshape(5000,5000), cmap=cm.gray)

In [31]:
tb = np.zeros((50,50))
tw = np.ones((50,50))
strips_h= np.tile(np.concatenate((np.concatenate((tb, tw), axis=0), np.concatenate((tb, tw), axis=0)) ,axis=1),(50,50)) 

In [34]:
plt.imsave('strips_h.png', np.array(strips_h).reshape(5000,5000), cmap=cm.gray)

In [10]:
a = np.asarray([[1,2,3],[4,5,6],[7,8,9], [10, 11, 12]])

In [13]:
np.mean(a, axis=0 ) 

array([5.5, 6.5, 7.5])

In [14]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
from scipy import signal
a_re = signal.resample(a, 2, axis=0)

In [16]:
a_re

array([[ 2.5,  3.5,  4.5],
       [ 8.5,  9.5, 10.5]])