In [56]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9]).reshape(9,1)
a.shape[1]+1

2

In [13]:
np.squeeze(a[3::]).shape

(6,)

In [44]:
r = np.random.random(10)
r

array([0.13651588, 0.77979092, 0.21041212, 0.83943877, 0.82796959,
       0.36354218, 0.14991681, 0.23856563, 0.87691686, 0.82844423])

In [46]:
mask = (r < 0.2)
mask

array([ True, False, False, False, False, False,  True, False, False,
       False])

In [25]:
mask*a

array([[1],
       [0],
       [3],
       [0],
       [5],
       [6],
       [0],
       [0],
       [9]])

In [26]:
mask*a/0.5

array([[ 2.],
       [ 0.],
       [ 6.],
       [ 0.],
       [10.],
       [12.],
       [ 0.],
       [ 0.],
       [18.]])

In [42]:
np.random.binomial(1000, 0.2, a.shape)/1000

array([[0.195],
       [0.206],
       [0.21 ],
       [0.189],
       [0.19 ],
       [0.209],
       [0.182],
       [0.184],
       [0.2  ]])

In [57]:
l = []

In [58]:
l.append(23)

In [59]:
l

[23]