In [1]:
import numpy as np

In [4]:
import numpy as np



######################################################## Constant ########################################################
class Constant:
    def __init__(self, constant_value = 0.1):
        self.constant_value = constant_value
        
    #def initialize(self, weights_shape, fan_in = None, fan_out = None):
    def initialize(self, weights_shape, fan_in, fan_out):  #ignore fan_in & fan_out
        
        return self.constant_value*(np.ones((weights_shape)))

########################################################### UniformRandom #####################################################    
    
class UniformRandom:
    def __init__(self):
        pass
    
    
    #def initialize(self, weights_shape, fan_in = None, fan_out = None):
    def initialize(self, weights_shape, fan_in, fan_out):  #ignore fan_in & fan_out
        return np.random.uniform(0, 1, weights_shape)

        
########################################################### Xavier/Glorot #####################################################        
class Xavier:
    def __init__(self):
        pass

    def initialize(self, weights_shape, fan_in, fan_out):
        sigma = np.sqrt(2/(fan_out+fan_in))
        #weights_shape = (weights_shape)
        return np.random.normal(0, sigma, weights_shape)

    
    
############################################################### He ######################################################
class He:
    def __init__(self):
        pass

    def initialize(self, weights_shape, fan_in, fan_out):
        sigma = np.sqrt(2/(fan_in))
        #weights_shape = (weights_shape)
        return np.random.normal(0, sigma, weights_shape)

In [8]:
#my_dist = UniformRandom()
UniformRandom().initialize((3,3), None, None)

array([[0.19760104, 0.85383613, 0.08918289],
       [0.61429478, 0.06239016, 0.18125249],
       [0.94219771, 0.20105806, 0.58909   ]])

In [13]:
np.random.uniform(0,1, (1, 5)).shape

(1, 5)

In [14]:
np.random.uniform(0,1, 5).shape

(5,)

In [15]:
input_size = 3
output_size = 5
weights_size = (input_size, output_size )

In [26]:
weights_wo_bias = np.random.uniform(0,1, weights_size) #without bias
#bias = np.random.uniform(0,1, (1,output_size))
bias = np.random.uniform(0,1, output_size)

In [34]:
weights = np.concatenate((weights_wo_bias, bias[None,:]),  axis=0)
weights

array([[0.68440136, 0.77147569, 0.2796086 , 0.40819604, 0.89216073],
       [0.99047666, 0.39369446, 0.6548207 , 0.48825245, 0.85251418],
       [0.61435514, 0.07306159, 0.31774959, 0.46568101, 0.50100382],
       [0.74362367, 0.978753  , 0.71548332, 0.80331313, 0.51701556]])

In [30]:
bias

array([0.74362367, 0.978753  , 0.71548332, 0.80331313, 0.51701556])

In [32]:
np.vstack((weights_wo_bias, bias)) == np.concatenate((weights_wo_bias, bias[None,:]),  axis=0)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [35]:
weights[:-1, :]

array([[0.68440136, 0.77147569, 0.2796086 , 0.40819604, 0.89216073],
       [0.99047666, 0.39369446, 0.6548207 , 0.48825245, 0.85251418],
       [0.61435514, 0.07306159, 0.31774959, 0.46568101, 0.50100382]])

In [37]:
weights[-1, :].shape

(5,)

In [41]:
np.zeros((input_size+1,output_size))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
a = np.array([[[1,7],[2,8]],[[3,9],[4,10]],[[5,11],[6,12]]])

In [51]:
b = a.flatten()
b

array([ 1,  7,  2,  8,  3,  9,  4, 10,  5, 11,  6, 12])

In [50]:
a

array([[[ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10]],

       [[ 5, 11],
        [ 6, 12]]])

In [52]:
b.reshape(a.shape)

array([[[ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10]],

       [[ 5, 11],
        [ 6, 12]]])

In [56]:
(a.shape[0], )

(3,)

In [79]:
f = 5

In [80]:
len(np.asarray(f))

TypeError: len() of unsized object

In [81]:
np.asarray([f])

array([5])

In [87]:
((1,)+(3,4))

(1, 3, 4)

In [168]:
np.expand_dims(a, 3)

array([[[[ 1],
         [ 7]],

        [[ 2],
         [ 8]]],


       [[[ 3],
         [ 9]],

        [[ 4],
         [10]]],


       [[[ 5],
         [11]],

        [[ 6],
         [12]]]])

In [91]:
a

array([[[ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10]],

       [[ 5, 11],
        [ 6, 12]]])

In [125]:
b.reshape((3,2,2,1))

array([[[[ 1],
         [ 7]],

        [[ 2],
         [ 8]]],


       [[[ 3],
         [ 9]],

        [[ 4],
         [10]]],


       [[[ 5],
         [11]],

        [[ 6],
         [12]]]])

In [95]:
b.reshape((3,2,2,1)).reshape((3,2,2))

array([[[ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10]],

       [[ 5, 11],
        [ 6, 12]]])

In [98]:
a[0,1,1]

8

In [101]:
for y in range(4, 4 + 5):
    print(y)

4
5
6
7
8


In [110]:
b.reshape((3,2,2,1))[0][:][0:2][0:2]

array([[[1],
        [7]],

       [[2],
        [8]]])

In [104]:
b

array([ 1,  7,  2,  8,  3,  9,  4, 10,  5, 11,  6, 12])

In [112]:
all_cc_output = []
all_cc_output

[]

In [113]:
list()

[]

In [114]:
t=(5,)

In [121]:
len(t)

1

In [123]:
t + t

(5, 5)

In [128]:
G = np.array([[1,2,3],
    [4,5,6],
    [7,8,9]])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [139]:
#H = np.array([[1,2],[4,5]])
H = np.array([[5]])
H

array([[5]])

In [134]:
import scipy
from scipy import signal


In [141]:
scipy.ndimage.correlate(H, G, None, 'constant')

array([[25]])

In [218]:
B = np.arange(0,144)
C = B.reshape([12, 12])
C

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131],
       [132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143]])

In [219]:
C[::8,::8]

array([[  0,   8],
       [ 96, 104]])

In [223]:
12 // 8

1

In [225]:
-(-12 // 4)

3

In [158]:
C[3 // 2][::2, ::2] #+ self.bias[i]

array([[100, 102, 104, 106, 108],
       [120, 122, 124, 126, 128],
       [140, 142, 144, 146, 148],
       [160, 162, 164, 166, 168],
       [180, 182, 184, 186, 188]])

In [ ]:
correlated[i] = temp[self.input_tensor.shape[1] // 2][::int(self.s1), ::int(self.s2)] + self.bias[i]

In [164]:
D = np.array([1,2,3,4]) +1

In [166]:
D[-1]

5

In [169]:
x = np.ones((1, 2, 3))

In [170]:
x

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [173]:
np.transpose(x, (1, 0, 2)).shape

(2, 1, 3)

In [179]:
np.flip(np.expand_dims(a, -1), axis = 1)

array([[[[ 2],
         [ 8]],

        [[ 1],
         [ 7]]],


       [[[ 4],
         [10]],

        [[ 3],
         [ 9]]],


       [[[ 6],
         [12]],

        [[ 5],
         [11]]]])

In [181]:
a

array([[[ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10]],

       [[ 5, 11],
        [ 6, 12]]])

In [180]:
np.expand_dims(a, -1)

array([[[[ 1],
         [ 7]],

        [[ 2],
         [ 8]]],


       [[[ 3],
         [ 9]],

        [[ 4],
         [10]]],


       [[[ 5],
         [11]],

        [[ 6],
         [12]]]])

In [192]:
np.transpose(np.expand_dims(a, -1), (1, 0, 2, 3))

array([[[[ 1],
         [ 7]],

        [[ 3],
         [ 9]],

        [[ 5],
         [11]]],


       [[[ 2],
         [ 8]],

        [[ 4],
         [10]],

        [[ 6],
         [12]]]])

In [196]:
np.flip(np.transpose(np.expand_dims(a, -1), (1, 0, 2, 3)), axis = 1).shape

(2, 3, 2, 1)

In [214]:
B = np.arange(0,300)
im = B.reshape([3, 10,10])
im

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [215]:
k = np.arange(0,27)
kernal = k.reshape([3, 3,3])
kernal

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [227]:
scipy.ndimage.convolve(im, kernal, None, 'constant').shape

(3, 10, 10)

In [230]:
im.shape[1:]

(10, 10)

In [232]:
scipy.signal.correlate(im,
                       np.expand_dims(kernal[0],0),
                       mode = "valid").shape

(3, 8, 8)

In [234]:
im.shape

(3, 10, 10)

In [237]:
np.expand_dims(kernal[0],0).reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [239]:
for i in range(5):
    print(i)

0
1
2
3
4


In [240]:
np.ones((5),d)

array([1., 1., 1., 1., 1.])

In [245]:
Dim = (10,3,20,20)
np.prod(np.asarray((1,2,3)))

6

In [247]:
np.asarray(Dim)[1:]

array([ 3, 20, 20])

In [248]:
a

array([[[ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10]],

       [[ 5, 11],
        [ 6, 12]]])

In [250]:
np.expand_dims(np.expand_dims(a, -1),0)

array([[[[[ 1],
          [ 7]],

         [[ 2],
          [ 8]]],


        [[[ 3],
          [ 9]],

         [[ 4],
          [10]]],


        [[[ 5],
          [11]],

         [[ 6],
          [12]]]]])