In [2]:
import numpy as np 
a = np.asarray([[1,2],[3,4]])

In [4]:
b = np.asarray([[1,2],[3,4]])

In [9]:
np.matmul(a, b) 

array([[ 7, 10],
       [15, 22]])

In [10]:
np.asarray([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [11]:
np.asarray([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])