In [1]:
import scipy.misc
import numpy as np
import matplotlib.pyplot as plt


class Sgd:
    def __init__(self, learning_rate):
        self.learning_rate = learning_rate
        
    def calculate_update(self, weight_tensor, gradient_tensor):
        return weight_tensor - self.learning_rate*gradient_tensor

In [ ]:
class FullyConnected:
    def __init__(self, input_size, output_size):
        self.input_size = input_size
        self.output_size = output_size
        self.weights_prim_size = (self.input_size+1, self.output_size ) # +1 for bias
        self.weight_prime = np.random.uniform(0,1,self.weights_prim_size) #Transposed whights matrix
        self.optimizer = None #learning rate
        
        
    def forward(self, input_tensor):
        input_tensor_prime = input_tensor
        batch_size = input_tensor_prime.shape[0]
        bias_factors = np.ones(batch_size) #np.ones(batch_size, dtype='int')
        self.input_tensor_prime_w_bias_factors = np.concatenate((input_tensor_prime, bias_factors[:,None]),  axis=1) #transposed inputs with ones as factors for bias
        
        return np.dot(input_tensor_prime_w_bias_factors , self.weight_prime)
    
    
    @property
    def set_optimizer(self):
        return self.optimizer
    @set_optimizer.setter
    def set_optimizer(self, optimizer):
        self.optimizer = optimizer
    
    
    def backward(self, error_tensor):
        error_tensor_prim = error_tensor
        error_tensor_next = np.dot(error_tensor_prim, self.weight_prime.T)
        self.grad_weight = np.dot(self.input_tensor_prime_w_bias_factors.T, error_tensor_prim)
        
        if self.optimizer != None:
            self.weight_prime = self.optimizer.calculate_update(self.weight_prime, self.grad_weight)
        
        return error_tensor_next
    
        
    @property
    def gradient_weights(self):
        return self.grad_weight

In [47]:
i = np.array([[1,2,3,12,43],[4,5,6,12,56],[7,8,9,12,52]])
i

array([[ 1,  2,  3, 12, 43],
       [ 4,  5,  6, 12, 56],
       [ 7,  8,  9, 12, 52]])

In [48]:
o = np.ones(i.shape[1])

In [71]:
i_1 = np.concatenate((i, o[:,None].T),  axis=0)
i_1

array([[ 1.,  2.,  3., 12., 43.],
       [ 4.,  5.,  6., 12., 56.],
       [ 7.,  8.,  9., 12., 52.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [68]:
i_1[i_1>10] = 0

In [69]:
i_1

array([[1., 2., 3., 0., 0.],
       [4., 5., 6., 0., 0.],
       [7., 8., 9., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [51]:
w = np.random.uniform(0,1,(4, i.shape[0]+1))
w

array([[0.26123953, 0.22275566, 0.80440724, 0.75912603],
       [0.26392119, 0.25424525, 0.75159542, 0.23682533],
       [0.11307371, 0.92077259, 0.33970381, 0.6942968 ],
       [0.28074939, 0.03582858, 0.46781135, 0.54248477]])

In [70]:
np.dot(w,i_1)[:,0:-1]

array([[ 7.54223887,  8.8306413 , 10.11904374,  0.75912603,  0.75912603],
       [ 6.77889542,  8.04865727,  9.31841913,  0.23682533,  0.23682533],
       [ 6.8683875 ,  8.24193761,  9.61548771,  0.6942968 ,  0.6942968 ],
       [ 4.24122796,  5.02561729,  5.81000662,  0.54248477,  0.54248477]])

In [75]:
(i_1 >= 10) * i_1 

#(self.input_tensor >= 0) * error_tensor

array([[ 0.,  0.,  0., 12., 43.],
       [ 0.,  0.,  0., 12., 56.],
       [ 0.,  0.,  0., 12., 52.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [40]:
lay = 3
in_siz = 5
w_siz = (lay, in_siz+1)
np.random.uniform(0,1,w_siz)

array([[0.82071732, 0.02536475, 0.50364928, 0.67611402, 0.82753202,
        0.49583446],
       [0.3781678 , 0.11089174, 0.84139971, 0.88469295, 0.38271595,
        0.17176547],
       [0.99068403, 0.205514  , 0.96835957, 0.17656044, 0.03116604,
        0.03869995]])

In [55]:
input_tensor_prime = np.array([[1,2,3,12,43],[4,5,6,12,56],[7,8,9,12,52]])
input_tensor_prime #three inputs each is size 5

array([[ 1,  2,  3, 12, 43],
       [ 4,  5,  6, 12, 56],
       [ 7,  8,  9, 12, 52]])

In [56]:
batch_size = input_tensor_prime.shape[0]
bias_factors = np.ones(batch_size) #np.ones(batch_size, dtype='int')


In [63]:
#input_tensor_prime_w_bias_factors = 
np.concatenate((input_tensor_prime, bias_factors[:,None]),  axis=1)

array([[ 1.,  2.,  3., 12., 43.,  1.],
       [ 4.,  5.,  6., 12., 56.,  1.],
       [ 7.,  8.,  9., 12., 52.,  1.]])

# ===============================================================

In [76]:
print(np.finfo(float).eps)

2.220446049250313e-16


In [91]:
i_1

array([[ 1.,  2.,  3., 12., 43.],
       [ 4.,  5.,  6., 12., 56.],
       [ 7.,  8.,  9., 12., 52.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [94]:
i_1 - np.max(i_1, axis=1)[:,None]

array([[-42., -41., -40., -31.,   0.],
       [-52., -51., -50., -44.,   0.],
       [-45., -44., -43., -40.,   0.],
       [  0.,   0.,   0.,   0.,   0.]])

In [98]:
np.sum(np.exp(i_1), axis=1)[:,None]

array([[4.72783947e+18],
       [2.09165950e+24],
       [3.83100800e+22],
       [1.35914091e+01]])

In [ ]:
np.log(input_tensor + np.finfo(float).eps)

In [99]:
 L = [0,10,20,40]


In [100]:
L

[40, 20, 10, 0]